server:
  servlet:
    context-path: "/api/v1"
spring:
  application:
    name: TwoChairsBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/twochairs
    username: twochairs
    password: twochairs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: on

  security:
    jwt:
      issuer: "twochairs"
      secret: "b3RZHJG3hlkRWRkUGQmK1WDfHDLKU8x1" # минимум 32+ символа
      accessTokenTtlSeconds: 2592000 # 30 дней

  devtools:
    livereload:
      enabled: true