spring:
  application:
    name: TwoChairsBackend

  datasource:
    url: jdbc:postgresql://localhost:5432/twochairs
    username: twochairs
    password: twochairs
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true